macro(MMP_SAMPLE_INI)

set(SAMPLE_WINDOWS_NAME "SDLWindow")
set(SAMPLE_GL_NAME "OPENGL")

if (NOT MMP_PRO_DIR)
    set(MMP_PRO_DIR ${MMP_PRO_TOP_DIR})
endif()

# config wrapper
if (USE_SDL)
    set(SAMPLE_WINDOWS_NAME "SDLWindow")
elseif (USE_EGL)
    set(SAMPLE_WINDOWS_NAME "EGLWindowDefault")
elseif (USE_D3D11)
    set(SAMPLE_WINDOWS_NAME "D3D11Window")
endif()
if (USE_OPENGL)
    set(SAMPLE_GL_NAME "OPENGL")
elseif(USE_D3D11)
    set(SAMPLE_GL_NAME "D3D11")
endif()
if (SAMPLE_SECTION_COMMON)
    set(INI_COMMON_SECTION_SWITCH "true")
else()
    set(INI_COMMON_SECTION_SWITCH "false")
endif()
if (SAMPLE_SECTION_GPU)
    set(INI_GPU_SECTION_SWITCH "true")
else()
    set(INI_GPU_SECTION_SWITCH "false")
endif()
if (SAMPLE_SECTION_CODEC)
    set(INI_CODEC_SECTION_SWITCH "true")
else()
    set(INI_CODEC_SECTION_SWITCH "false")
endif()
if (SAMPLE_SECTION_ULTIS)
    set(INI_ULTIS_SECTION_SWITCH "true")
else()
    set(INI_ULTIS_SECTION_SWITCH "false")
endif()
if (USE_API_RPC)
    set(INI_RPC_SECTION_SWITCH "true")
else()
    set(INI_RPC_SECTION_SWITCH "false")
endif()
if (SAMPLE_SECTION_PLUGIN_TRANSITION)
    set(INI_PLUGIN_TRANSITION_SECTION_SWITCH "true")
else()
    set(INI_PLUGIN_TRANSITION_SECTION_SWITCH "false")
endif()
if (SAMPLE_SECTION_PLUGIN_CSC)
    set(INI_PLUGIN_CSC_SECTION_SWITCH "true")
else()
    set(INI_PLUGIN_CSC_SECTION_SWITCH "false")
endif()

configure_file(${MMP_PRO_TOP_DIR}/Sample/Sample.ini.in ${MMP_PRO_TOP_DIR}/Sample/Sample.ini)
endmacro()