macro(MMP_SPRIV_CROSS_CONFIG)
    if (USE_SPRIV_CROSS)
        set(SPIRV_CROSS_SKIP_INSTALL ON)
        set(SPIRV_CROSS_CLI OFF)
        set(SPIRV_CROSS_ENABLE_TESTS OFF)
        set(SPIRV_CROSS_ENABLE_C_API OFF)
        add_subdirectory(Extension/SPIRV-Cross)
    endif()
endmacro()